---
title: 'M12 Group Work: Simple Linear Regression for TAs'
author: "Pablo E. Gutiérrez-Fonseca"
date: "2024-04-18"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(car)
```

#Load data
```{r}
BAI_NDWI <- read_xlsx("PIRU_BAI.xlsx")
```

#This makes a plot with our regression line.
```{r}
ggplot(BAI_NDWI) +
  aes(x = min_NDWI, y = BAI) +
  geom_point() +
  theme(legend.position = "none") + 
  stat_smooth(method = "lm", formula = y ~ x, geom = "smooth") 
```

#this simply creates a 'model' for our regression model
#This is the main think we are looking at!
```{r}
model <- lm(BAI ~ min_NDWI , data = BAI_NDWI)
summary(model)
```


##the Breusch-Pagan test to assess homoscedasticity
```{r}
ncvTest(model)
```

#get list of residuals to nest normality
```{r}
res <- resid(model)
shapiro.test(res)

```

#create residual plot
```{r}
ggplot(model, aes(x = .fitted, y = .resid)) +
  geom_point(size=3) +  
  geom_hline(yintercept = 0, color = "red") +
  labs(title = "Residuals Plot",
       x = "Index",
       y = "Residuals")
```


#RMSE
```{r}
RMSE <- sqrt(sum(model$residuals^2)/model$df)
RMSE
```

```{r}
response <- BAI_NDWI$BAI
# Calculate the Mean of the response
mean_response <- mean(response)
Percentage_Error <- RMSE/mean_response
Percentage_Error
```

#PRESS
```{r}
# (r <- resid(mod))
pr <- resid(model)/(1 - lm.influence(model)$hat)
PRESS <- sum(pr^2)
PRESS

# PRESS_RMSE
PRESS_RMSE <- sqrt(PRESS/length(model$residuals))
PRESS_RMSE
```


```{r}
#Jackknifing
jack.reg<-numeric(27)
for (i in 1:27) {
  model<-lm(BAI[-i]~min_NDWI[-i], data = BAI_NDWI)
  jack.reg[i]<-summary(model)$r.squared }

ggplot(as.tibble(jack.reg), aes(value)) + geom_histogram()

shapiro.test(jack.reg)
```

