---
title: 'M10 Group Work: One Way ANOVA for TAs'
author: "Pablo E. Gutiérrez-Fonseca"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output: pdf_document
---


#1. Import libraries and load packages
```{r message=FALSE}
library(tidyverse)
library(rstatix)
library(readxl)
library(dplyr)
library(PMCMRplus)
```



#2. Importing our data
```{r}
UV_deformities <- read.csv(file = "UV_deformities.csv", header = TRUE)
```


#3.Normality
```{r}
shapiro.test(UV_deformities$deformities)
```

#4. #variance
```{r}
bartlett.test(deformities ~ species, data = UV_deformities)
```

#5. boxplot
```{r}
ggplot(UV_deformities) + aes(x = species, y = deformities) + 
          geom_boxplot() 
```

#4. Run a kruskal.test
# NOT Normal AND NON-Equal Variances
```{r}
kruskal.test(deformities ~ species, data = UV_deformities)
#All Pairs
wilcox_test(deformities ~ species, data = UV_deformities, p.adjust.method = "bonferroni")
#Effect Size
kruskal_effsize(deformities ~ species, data = UV_deformities)

```

#5. Another way to find R^2
```{r}
mod <- aov(deformities ~ species, data = UV_deformities)
summary(mod)
18047 / (18047+9460)

summary(lm(deformities ~ species, data = UV_deformities))
```

